# Generated by Django 5.2.8 on 2025-12-11 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('periodo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('calificacion', models.CharField(max_length=50)),
                ('fuente', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('factor_08', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_09', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_10', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_11', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_20', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_37', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_12', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_13', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_14', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_15', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_16', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_17', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_18', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_19', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_21', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_22', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_23', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_24', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_25', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_26', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_27', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_28', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_29', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_30', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_31', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_32', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_33', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_34', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_35', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('factor_36', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('corredor', 'Corredor'), ('admin', 'Administrador'), ('auditor', 'Auditor externo')], default='corredor', max_length=20)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
